name: todo_up_backend
description: Local backend for the ToDoUp Flutter application.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  path: ^1.9.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.1.1
